/**
 * Conference Data
 * This file contains all conference information.
 * In production, this will be auto-generated by GitHub Actions + Gemini
 */

const CONFERENCES_DATA = {
    lastUpdated: "2026-01-30T00:00:00Z",
    conferences: [
        // ============================================
        // MACHINE LEARNING
        // ============================================
        {
            id: "icml-2026",
            name: "ICML",
            fullName: "International Conference on Machine Learning",
            year: 2026,
            category: "ml",
            website: "https://icml.cc/",
            brandColor: "#1E3A5F",
            location: {
                city: "Seoul",
                country: "South Korea",
                flag: "🇰🇷",
                venue: "Coex Convention Center"
            },
            deadlines: [
                { type: "abstract", label: "Abstract", date: "2026-01-23T23:59:00-12:00", status: "passed" },
                { type: "paper", label: "Paper Submission", date: "2026-01-30T23:59:00-12:00", status: "active" },
                { type: "notification", label: "Notification", date: "2026-05-01T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "camera", label: "Camera Ready", date: "2026-06-15T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "event", label: "Conference", date: "2026-07-06", endDate: "2026-07-11", status: "upcoming" }
            ],
            links: {
                official: "https://icml.cc/Conferences/2026",
                author: "https://icml.cc/Conferences/2026/CallForPapers",
                submission: "https://openreview.net/group?id=ICML.cc/2026/Conference",
                template: "https://icml.cc/Conferences/2026/StyleFiles",
                authorGuide: "https://icml.cc/Conferences/2026/AuthorGuidelines"
            },
            info: {
                pageLimit: "9 pages",
                reviewType: "Double-blind",
                acceptanceRate: "~25%"
            },
            notes: [
                "Supplementary materials allowed (no page limit)",
                "Code submission encouraged but not required",
                "No author names or affiliations in submission"
            ],
            deskRejectReasons: [
                "Exceeds 9-page limit (excluding references)",
                "Author names visible in PDF or metadata",
                "Not using official ICML LaTeX template",
                "Submission already published elsewhere"
            ]
        },
        {
            id: "iclr-2026",
            name: "ICLR",
            fullName: "International Conference on Learning Representations",
            year: 2026,
            category: "ml",
            website: "https://iclr.cc/",
            brandColor: "#008B8B",
            location: {
                city: "Rio de Janeiro",
                country: "Brazil",
                flag: "🇧🇷",
                venue: "TBD"
            },
            deadlines: [
                { type: "abstract", label: "Abstract", date: "2025-09-19T23:59:00-12:00", status: "passed" },
                { type: "paper", label: "Paper Submission", date: "2025-09-24T23:59:00-12:00", status: "passed" },
                { type: "notification", label: "Notification", date: "2026-01-22T23:59:00-12:00", status: "passed" },
                { type: "camera", label: "Camera Ready", date: "2026-03-01T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "event", label: "Conference", date: "2026-04-23", endDate: "2026-04-27", status: "upcoming" }
            ],
            links: {
                official: "https://iclr.cc/Conferences/2026",
                author: "https://iclr.cc/Conferences/2026/AuthorGuide",
                submission: "https://openreview.net/group?id=ICLR.cc/2026/Conference",
                template: "https://github.com/ICLR/Master-Template"
            },
            info: {
                pageLimit: "10 pages",
                reviewType: "Open review",
                acceptanceRate: "~30%"
            },
            notes: [
                "Open peer review on OpenReview",
                "Rebuttals allowed",
                "Unlimited appendix pages"
            ]
        },
        {
            id: "neurips-2026",
            name: "NeurIPS",
            fullName: "Conference on Neural Information Processing Systems",
            year: 2026,
            category: "ml",
            website: "https://neurips.cc/",
            brandColor: "#6B2D73",
            location: {
                city: "TBD",
                country: "TBD",
                flag: "🌍",
                venue: "TBD"
            },
            deadlines: [
                { type: "abstract", label: "Abstract", date: "2026-05-11T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "paper", label: "Paper Submission", date: "2026-05-15T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "supplementary", label: "Supplementary", date: "2026-05-22T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "notification", label: "Notification", date: "2026-09-18T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "event", label: "Conference", date: "2026-12-06", endDate: "2026-12-12", status: "upcoming", estimated: true }
            ],
            links: {
                official: "https://neurips.cc/Conferences/2026",
                author: "https://neurips.cc/Conferences/2026/CallForPapers"
            }
        },
        {
            id: "aaai-2026",
            name: "AAAI",
            fullName: "AAAI Conference on Artificial Intelligence",
            year: 2026,
            category: "ml",
            website: "https://aaai.org/",
            brandColor: "#003366",
            location: {
                city: "Philadelphia",
                country: "USA",
                flag: "🇺🇸",
                venue: "Pennsylvania Convention Center"
            },
            deadlines: [
                { type: "abstract", label: "Abstract", date: "2025-08-07T23:59:00-12:00", status: "passed" },
                { type: "paper", label: "Paper Submission", date: "2025-08-15T23:59:00-12:00", status: "passed" },
                { type: "notification", label: "Notification", date: "2025-12-09T23:59:00-12:00", status: "passed" },
                { type: "event", label: "Conference", date: "2026-02-17", endDate: "2026-02-25", status: "upcoming" }
            ],
            links: {
                official: "https://aaai.org/conference/aaai/aaai-26/",
                author: "https://aaai.org/conference/aaai/aaai-26/aaai-26-call-for-papers/"
            }
        },
        {
            id: "aistats-2026",
            name: "AISTATS",
            fullName: "International Conference on AI and Statistics",
            year: 2026,
            category: "ml",
            website: "https://aistats.org/",
            brandColor: "#2E5984",
            location: {
                city: "TBD",
                country: "TBD",
                flag: "🌍",
                venue: "TBD"
            },
            deadlines: [
                { type: "abstract", label: "Abstract", date: "2025-10-03T23:59:00-12:00", status: "passed", estimated: true },
                { type: "paper", label: "Paper Submission", date: "2025-10-10T23:59:00-12:00", status: "passed", estimated: true },
                { type: "notification", label: "Notification", date: "2026-01-15T23:59:00-12:00", status: "passed", estimated: true },
                { type: "event", label: "Conference", date: "2026-04-01", endDate: "2026-04-03", status: "upcoming", estimated: true }
            ],
            links: {
                official: "https://aistats.org/aistats2026/"
            }
        },
        {
            id: "ijcai-2026",
            name: "IJCAI",
            fullName: "International Joint Conference on AI",
            year: 2026,
            category: "ml",
            website: "https://ijcai.org/",
            brandColor: "#C41E3A",
            location: {
                city: "Montreal",
                country: "Canada",
                flag: "🇨🇦",
                venue: "TBD"
            },
            deadlines: [
                { type: "abstract", label: "Abstract", date: "2026-01-16T23:59:00-12:00", status: "passed" },
                { type: "paper", label: "Paper Submission", date: "2026-01-23T23:59:00-12:00", status: "passed" },
                { type: "notification", label: "Notification", date: "2026-04-16T23:59:00-12:00", status: "upcoming" },
                { type: "event", label: "Conference", date: "2026-08-08", endDate: "2026-08-14", status: "upcoming" }
            ],
            links: {
                official: "https://ijcai-26.org/",
                author: "https://ijcai-26.org/call-for-papers/"
            }
        },

        // ============================================
        // COMPUTER VISION
        // ============================================
        {
            id: "cvpr-2026",
            name: "CVPR",
            fullName: "Computer Vision and Pattern Recognition",
            year: 2026,
            category: "cv",
            website: "https://cvpr.thecvf.com/",
            brandColor: "#CC0000",
            location: {
                city: "Denver",
                country: "USA",
                flag: "🇺🇸",
                venue: "Denver Convention Center"
            },
            deadlines: [
                { type: "abstract", label: "Abstract", date: "2025-11-07T23:59:00-12:00", status: "passed" },
                { type: "paper", label: "Paper Submission", date: "2025-11-13T23:59:00-12:00", status: "passed" },
                { type: "supplementary", label: "Supplementary", date: "2025-11-20T23:59:00-12:00", status: "passed" },
                { type: "notification", label: "Notification", date: "2026-02-20T23:59:00-12:00", status: "upcoming" },
                { type: "event", label: "Conference", date: "2026-06-03", endDate: "2026-06-07", status: "upcoming" }
            ],
            links: {
                official: "https://cvpr.thecvf.com/Conferences/2026",
                author: "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
                submission: "https://openreview.net/group?id=thecvf.com/CVPR/2026/Conference"
            }
        },
        {
            id: "eccv-2026",
            name: "ECCV",
            fullName: "European Conference on Computer Vision",
            year: 2026,
            category: "cv",
            website: "https://eccv.ecva.net/",
            brandColor: "#2E8B57",
            location: {
                city: "Milan",
                country: "Italy",
                flag: "🇮🇹",
                venue: "MiCo Convention Center"
            },
            deadlines: [
                { type: "paper", label: "Paper Submission", date: "2026-03-05T23:59:00-12:00", status: "upcoming" },
                { type: "supplementary", label: "Supplementary", date: "2026-03-12T23:59:00-12:00", status: "upcoming" },
                { type: "notification", label: "Notification", date: "2026-06-01T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "event", label: "Conference", date: "2026-09-29", endDate: "2026-10-04", status: "upcoming" }
            ],
            links: {
                official: "https://eccv2026.ecva.net/"
            }
        },
        {
            id: "iccv-2025",
            name: "ICCV",
            fullName: "International Conference on Computer Vision",
            year: 2025,
            category: "cv",
            website: "https://iccv.thecvf.com/",
            brandColor: "#0066CC",
            location: {
                city: "Honolulu",
                country: "USA",
                flag: "🇺🇸",
                venue: "Hawaii Convention Center"
            },
            deadlines: [
                { type: "paper", label: "Paper Submission", date: "2025-03-14T23:59:00-12:00", status: "passed" },
                { type: "notification", label: "Notification", date: "2025-07-01T23:59:00-12:00", status: "passed" },
                { type: "event", label: "Conference", date: "2025-10-19", endDate: "2025-10-25", status: "passed" }
            ],
            links: {
                official: "https://iccv2025.thecvf.com/"
            }
        },
        {
            id: "wacv-2026",
            name: "WACV",
            fullName: "Winter Conference on Applications of Computer Vision",
            year: 2026,
            category: "cv",
            website: "https://wacv2026.thecvf.com/",
            brandColor: "#4A90A4",
            location: {
                city: "Tucson",
                country: "USA",
                flag: "🇺🇸",
                venue: "TBD"
            },
            deadlines: [
                { type: "paper", label: "Paper Submission", date: "2025-07-18T23:59:00-12:00", status: "passed" },
                { type: "notification", label: "Notification", date: "2025-10-15T23:59:00-12:00", status: "passed" },
                { type: "event", label: "Conference", date: "2026-02-28", endDate: "2026-03-04", status: "upcoming" }
            ],
            links: {
                official: "https://wacv2026.thecvf.com/"
            }
        },

        // ============================================
        // NLP
        // ============================================
        {
            id: "acl-2026",
            name: "ACL",
            fullName: "Annual Meeting of the ACL",
            year: 2026,
            category: "nlp",
            website: "https://www.aclweb.org/",
            brandColor: "#FF6600",
            location: {
                city: "San Diego",
                country: "USA",
                flag: "🇺🇸",
                venue: "Convention Center"
            },
            deadlines: [
                { type: "paper", label: "ARR Submission", date: "2026-02-15T23:59:00-12:00", status: "upcoming", note: "Via ACL Rolling Review" },
                { type: "commitment", label: "Commitment Deadline", date: "2026-03-14T23:59:00-12:00", status: "upcoming" },
                { type: "notification", label: "Notification", date: "2026-04-04T23:59:00-12:00", status: "upcoming" },
                { type: "event", label: "Conference", date: "2026-07-02", endDate: "2026-07-07", status: "upcoming" }
            ],
            links: {
                official: "https://2026.aclweb.org/",
                submission: "https://openreview.net/group?id=aclweb.org/ACL/ARR"
            }
        },
        {
            id: "emnlp-2025",
            name: "EMNLP",
            fullName: "Empirical Methods in Natural Language Processing",
            year: 2025,
            category: "nlp",
            website: "https://www.aclweb.org/",
            brandColor: "#228B22",
            location: {
                city: "Miami",
                country: "USA",
                flag: "🇺🇸",
                venue: "TBD"
            },
            deadlines: [
                { type: "paper", label: "ARR Submission", date: "2025-06-15T23:59:00-12:00", status: "passed", note: "Via ACL Rolling Review" },
                { type: "commitment", label: "Commitment Deadline", date: "2025-08-01T23:59:00-12:00", status: "passed" },
                { type: "event", label: "Conference", date: "2025-11-12", endDate: "2025-11-16", status: "passed", estimated: true }
            ],
            links: {
                official: "https://2025.emnlp.org/"
            }
        },
        {
            id: "naacl-2025",
            name: "NAACL",
            fullName: "North American Chapter of the ACL",
            year: 2025,
            category: "nlp",
            website: "https://naacl.org/",
            brandColor: "#9932CC",
            location: {
                city: "Albuquerque",
                country: "USA",
                flag: "🇺🇸",
                venue: "Convention Center"
            },
            deadlines: [
                { type: "paper", label: "ARR Submission", date: "2024-12-15T23:59:00-12:00", status: "passed" },
                { type: "commitment", label: "Commitment Deadline", date: "2025-02-20T23:59:00-12:00", status: "passed" },
                { type: "event", label: "Conference", date: "2025-04-29", endDate: "2025-05-04", status: "passed" }
            ],
            links: {
                official: "https://2025.naacl.org/"
            }
        },

        // ============================================
        // SPEECH & SIGNAL
        // ============================================
        {
            id: "interspeech-2025",
            name: "Interspeech",
            fullName: "Annual Conference of ISCA",
            year: 2025,
            category: "speech",
            website: "https://www.interspeech2025.org/",
            brandColor: "#E67E22",
            location: {
                city: "Rotterdam",
                country: "Netherlands",
                flag: "🇳🇱",
                venue: "Ahoy Rotterdam"
            },
            deadlines: [
                { type: "paper", label: "Paper Submission", date: "2025-03-01T23:59:00-12:00", status: "passed" },
                { type: "notification", label: "Notification", date: "2025-06-01T23:59:00-12:00", status: "passed" },
                { type: "event", label: "Conference", date: "2025-08-24", endDate: "2025-08-28", status: "passed" }
            ],
            links: {
                official: "https://www.interspeech2025.org/"
            }
        },
        {
            id: "icassp-2026",
            name: "ICASSP",
            fullName: "IEEE Conference on Acoustics, Speech, and Signal Processing",
            year: 2026,
            category: "speech",
            website: "https://2026.ieeeicassp.org/",
            brandColor: "#FF8C00",
            location: {
                city: "Hyderabad",
                country: "India",
                flag: "🇮🇳",
                venue: "HICC"
            },
            deadlines: [
                { type: "paper", label: "Paper Submission", date: "2025-10-01T23:59:00-12:00", status: "passed", estimated: true },
                { type: "notification", label: "Notification", date: "2026-01-15T23:59:00-12:00", status: "passed", estimated: true },
                { type: "event", label: "Conference", date: "2026-04-06", endDate: "2026-04-11", status: "upcoming" }
            ],
            links: {
                official: "https://2026.ieeeicassp.org/"
            }
        },

        // ============================================
        // OTHER
        // ============================================
        {
            id: "kdd-2026",
            name: "KDD",
            fullName: "Knowledge Discovery and Data Mining",
            year: 2026,
            category: "other",
            website: "https://kdd.org/",
            brandColor: "#CC0066",
            location: {
                city: "TBD",
                country: "TBD",
                flag: "🌍",
                venue: "TBD"
            },
            deadlines: [
                { type: "paper", label: "Paper Submission", date: "2026-02-01T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "notification", label: "Notification", date: "2026-05-01T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "event", label: "Conference", date: "2026-08-02", endDate: "2026-08-06", status: "upcoming", estimated: true }
            ],
            links: {
                official: "https://kdd.org/kdd2026/"
            }
        },
        {
            id: "siggraph-2026",
            name: "SIGGRAPH",
            fullName: "ACM SIGGRAPH Annual Conference",
            year: 2026,
            category: "other",
            website: "https://s2026.siggraph.org/",
            brandColor: "#1ABC9C",
            location: {
                city: "Vancouver",
                country: "Canada",
                flag: "🇨🇦",
                venue: "Convention Center"
            },
            deadlines: [
                { type: "paper", label: "Paper Submission", date: "2026-01-23T23:59:00-12:00", status: "passed", estimated: true },
                { type: "notification", label: "Notification", date: "2026-04-15T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "event", label: "Conference", date: "2026-08-09", endDate: "2026-08-13", status: "upcoming", estimated: true }
            ],
            links: {
                official: "https://s2026.siggraph.org/"
            }
        },
        {
            id: "miccai-2026",
            name: "MICCAI",
            fullName: "Medical Image Computing and Computer Assisted Intervention",
            year: 2026,
            category: "other",
            website: "https://miccai.org/",
            brandColor: "#FF2D55",
            location: {
                city: "TBD",
                country: "TBD",
                flag: "🌍",
                venue: "TBD"
            },
            deadlines: [
                { type: "paper", label: "Paper Submission", date: "2026-03-01T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "notification", label: "Notification", date: "2026-06-01T23:59:00-12:00", status: "upcoming", estimated: true },
                { type: "event", label: "Conference", date: "2026-10-04", endDate: "2026-10-08", status: "upcoming", estimated: true }
            ],
            links: {
                official: "https://conferences.miccai.org/2026/"
            }
        },
        {
            id: "mlsys-2026",
            name: "MLSys",
            fullName: "Conference on Machine Learning and Systems",
            year: 2026,
            category: "other",
            website: "https://mlsys.org/",
            brandColor: "#34495E",
            location: {
                city: "TBD",
                country: "TBD",
                flag: "🌍",
                venue: "TBD"
            },
            deadlines: [
                { type: "paper", label: "Paper Submission", date: "2025-10-10T23:59:00-12:00", status: "passed", estimated: true },
                { type: "notification", label: "Notification", date: "2026-01-20T23:59:00-12:00", status: "passed", estimated: true },
                { type: "event", label: "Conference", date: "2026-05-01", endDate: "2026-05-04", status: "upcoming", estimated: true }
            ],
            links: {
                official: "https://mlsys.org/"
            }
        }
    ]
};

// Category metadata
const CATEGORIES = {
    ml: { name: "Machine Learning", color: "#AF52DE" },
    cv: { name: "Computer Vision", color: "#007AFF" },
    nlp: { name: "NLP", color: "#34C759" },
    speech: { name: "Speech & Audio", color: "#FF9500" },
    other: { name: "Other", color: "#8E8E93" }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CONFERENCES_DATA, CATEGORIES };
}
